version: 1.0.{build}
image: Visual Studio 2017
build: off
notifications:
- provider: Email
  to:
  - maic23@live.de
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
environment:
  PATH: 'C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%'
  PYTHONUTF8: 1
install:
  pip install pyzmq
before_test:
  - git clone https://github.com/bitcoin/bitcoin.git --depth 1
  - cd bitcoin
  - set SRCDIR=%CD%
  - cd ..
  - python .\download_latest_nightly.py > output
  - type output
  - ps: ${env:BUILDDIR}=(Get-Content -Tail 1 output)
test_script:
  - '%BUILDDIR%\src\test_bitcoin.exe'
  - python %SRCDIR%\test\util\bitcoin-util-test.py -v
  - python %SRCDIR%\test\functional\test_runner.py --extended --coverage -x feature_pruning,feature_dbcrash,wallet_backup,feature_block --force --combinedlogslen=4000
after_test:
  - cd %SRCDIR%
  - git log -1
  - cd %BUILDDIR%
  - Get-FileHash .\src\*
deploy: off
